query GET_POST {
  post {
    id
    title
  }
}

query GET_POSTS {
  posts {
    id
    title
  }
}

query GET_USERS {
  user {
    id
    userName
  }
}

query GET_USERS {
  users {
    id
    userName
  }
}